version: '3'

services:
  mysql:
    image: mysql:8.0.34
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./scripts/mysql_data/backup.sql:/docker-entrypoint-initdb.d/backup.sql
    networks:
      - greeting-network
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./scripts/mongo_data:/scripts/mongo_data

    networks:
      - greeting-network

  server:
    build: 
      context: .
    container_name: backend
    restart: always
    ports:
      - "7070:7070"
    networks:
      - greeting-network

volumes:
  mysql-data:
  mongo-data:
   
networks:
  greeting-network:
    driver: bridge