version: '3'

services:
  mysql:
    image: mysql:8.0.34
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - greeting-network

  # server:
  #   build: 
  #     context: .
  #   container_name: backend
  #   restart: always
  #   ports:
  #     - "7070:7070"

volumes:
  mysql-data:
   
networks:
  greeting-network:
    driver: bridge