name: CI Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        poetry --version

    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Export requirements.txt from poetry.lock
      shell: bash
      run: |
        poetry export --output requirements.txt 

    - name: Build Docker image & Run tests
      run: |
        docker build -t greeting:latest .
        docker run --rm -e SKIP_API_TESTS=true greeting:latest bash -c "export PYTHONPATH=../Birthday_Greeting_Kata && pytest"

